#page title
page_title                                : Welcome to Nimses / 2500 free Nims on sign up / Nimses invite code ZN2VAM # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1201745929                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.nimses                                          # Enter Google Play Store URL.
presskit_download_link                    : https://web.nimses.com/profile/saeeed                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Get ahead with one day's worth of Nims (2500 free Nims) by signing up using code ZN2VAM. 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nimses                                
your_link                                 : https://nimses.com                     
your_city                                 : Delaware                                
email_address                             : support@nimses.com
facebook_username                         : nimses                                          
instagram_username                        : nimses
twitter_username                          : nimses
#github_username                           : nimses
#youtube_username                          : nimses



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : How does the NIM or (virtual currency) work?
    description                           : For each day, a NIM grows automatically by 1440 – the exact number of minutes in 24 hours. So in a month, a user will accumulate 43,830 without doing anything. You can use these NIMs with participating vendors to purchase anything you want. As popularly grows, more and more vendors are excepting Nims as currency. Don’t forget the invite code when you register because you will lose out on the offer. Nimses does not have a way to backtrack the registration process.
    fontawesome_icon_name                 : money-bill-wave
    
  - title                                 : What is Nimses?
    description                           : Nimses is a worldwide system which records and saves the time of a human being’s life. After the user registers an account with Nimses, each minute of the person’s life turns into a single Nim, a unique and indestructible unit of digital currency. The total number of Nims produced and gained by one person is accumulated into their individual account balance, called the Nimb. One can manage their personal Nimb through the free, location-based Nimses App.
    fontawesome_icon_name                 : question
    
  - title                                 : How to grow your Nimses account?
    description                           : Spam users for nom for nom. Spam the pewdiepie comment section with "nom4nom". Use the Nimses invite code to invite family and friends to register for an account. Nimses does not impose a limit for invites; so invite as many humans as you can. At this time, invitations receive the most NIMs than all other activity within the app.
    fontawesome_icon_name                 : seedling    



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#ffffff"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#ffffff"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#000000"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#ffffff"

footer_text_color                         : "#ffffff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
